// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/googlesheets/sheets.go

// Package mock_googlesheets is a generated GoMock package.
package mock_googlesheets

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sheets "google.golang.org/api/sheets/v4"
)

// MockSheet is a mock of Sheet interface.
type MockSheet struct {
	ctrl     *gomock.Controller
	recorder *MockSheetMockRecorder
}

// MockSheetMockRecorder is the mock recorder for MockSheet.
type MockSheetMockRecorder struct {
	mock *MockSheet
}

// NewMockSheet creates a new mock instance.
func NewMockSheet(ctrl *gomock.Controller) *MockSheet {
	mock := &MockSheet{ctrl: ctrl}
	mock.recorder = &MockSheetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSheet) EXPECT() *MockSheetMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSheet) Get(rang string) (*sheets.ValueRange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", rang)
	ret0, _ := ret[0].(*sheets.ValueRange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSheetMockRecorder) Get(rang interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSheet)(nil).Get), rang)
}
